version: '3'
services:
  ola:
    build: .
    ports:
      - "4000:80"
    networks:
      - "rede"
  redis:
    image: "redis"
    networks:
      - "rede"
    ports: 
      - 5432:5432
    volumes: 
      - dados:/var/lib/postgresql/data
      

networks:
  rede:

volumes:
  dados:
