version: '3'
services:
  hello:
    build: .
    ports:
      - "4000:80"
    networks:
      - "rede"
  hello_db:
    image: "postgres:11"
    networks:
      - "rede"
    ports: 
      - 5432:5432
    volumes: 
      - dados:/var/lib/postgresql/data
      

networks:
  rede:

volumes:
  dados:
