version: '3'
services:
  hello:
    build: .
    ports:
      - "4000"
    networks:
      - "rede"
    labels:
      - "traefik.backend=ola"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:localhost"
    depends_on: 
      - redis
  hello_db:
    image: "redis"
    ports:
      - 5432:5432
    networks:
      - "redis"
    volumes: 
      - dados:/var/lib/postgresql/data
  lb:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=localhost --logLevel=INFO 
    ports:
      - 4000:80
      - 8080:8080
    networks:
      - "rede"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  rede:

volumes:
  dados:
