version: '3'
services:
  ola:
    build: .
    ports:
      - "4000"
    networks:
      - "rede"
    labels:
      - "traefik.backend=ola"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:localhost"
    depends_on: 
      - redis
  redis:
    image: "redis"
    networks:
      - "rede"
  lb:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=localhost --logLevel=INFO 
    ports:
      - 4000:80
      - 8080:8080
    networks:
      - "rede"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  rede:
