version: '3'
services:
  hello:
    build: .
    ports:
      - "4000:80"
    networks:
      - "workshop"
  hello_db:
    image: "postgres:11"
    networks:
      - "workshop"
    ports: 
      - 5432:5432
    volumes: 
      - workshop_data:/var/lib/postgresql/data
      

networks:
  workshop:

volumes:
  workshop_data:
